### ISSUE TITLE
Error 500 internal Server Error

### ISSUE THREAD

**Issue by solomongs** [abhisarahuja/Integrate_ChatGPT_in_Whatsapp#2]
PS C:\Python Project\Whatsapp> python server.py
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a product production WSGI server instead.
 * Running on http://127.0.0.1:5001
Press CTRL+C to quit
Sending message:  Hi
[2023-05-31 06:18:14,865] ERROR in app: Exception on /chat [GET]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Python Project\Whatsapp\server.py", line 60, in chat
    response = get_last_message()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python Project\Whatsapp\server.py", line 52, in get_last_message
    last_element = page_elements[-2]
                   ~~~~~~~~~~~~~^^^^
IndexError: list index out of range
127.0.0.1 - - [31/May/2023 06:18:14] "GET /chat?q=Hi HTTP/1.1" 500 -
Sending message:  Hello
[2023-05-31 06:18:28,966] ERROR in app: Exception on /chat [GET]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python Project\Whatsapp\server.py", line 60, in chat
    response = get_last_message()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python Project\Whatsapp\server.py", line 52, in get_last_message
    last_element = page_elements[-2]
                   ~~~~~~~~~~~~~^^^^
IndexError: list index out of range
127.0.0.1 - - [31/May/2023 06:18:28] "GET /chat?q=Hello HTTP/1.1" 500 -
Sending message:  Hihi
[2023-05-31 06:19:27,456] ERROR in app: Exception on /chat [GET]

**Comment by emrahgmrk** [comment]
did you solve it? I've got the same error.
